dist: trusty
sudo: required
services:
  - docker

env:
    global:
        - DOCKER_VERSION=1.13.1-0~ubuntu-trusty

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine=${DOCKER_VERSION}
  - docker version
  - docker info
  # install bats
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  # prepare docker images
  - make update-dependencies

matrix:
  include:
    - env: TEST_ID=test-debian
    - env: TEST_ID=test-alpine
    - env: TEST_ID=test2-debian
    - env: TEST_ID=test2-alpine
  allow_failures:
    - env: TEST_ID=test2-debian
    - env: TEST_ID=test2-alpine

script:
  - make $TEST_ID
