name: Test

on: [push, pull_request]

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        docker_image: [alpine, debian]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python-requirements.txt
        working-directory: test/requirements

      - name: Build Docker web server image
        run: make update-dependencies

      - name: Run tests
        run: make test-${{ matrix.docker_image }}
